/**
 * Per-state demographic vote splits for the State Analyzer's no-poll baseline,
 * as the Democratic two-party share of each group (0..1). Generated by
 * scripts/build-state-splits.mjs (npm run build:state-splits) by ridge
 * ecological regression of each state's district-level 2024 presidential
 * results (scripts/party/pres_by_cd.csv) on its ACS district composition
 * (public/data/demographics.json), partially pooled toward the national 2024
 * exit-poll group splits and recentered so the VAP-weighted state result
 * matches the state's actual 2024 vote. Party ID is absent by design; it keeps
 * the shifted national baseline. Each value is a 2024 result; the app applies
 * the 2026 environment shift, by subgroup (src/data/nationalSwing.ts).
 */
export const STATE_SPLITS: Record<
  string,
  Record<string, Record<string, number>>
> = {
  "01": {
      sex: { "male": 0.2955, "female": 0.3946 },
      age: { "18-29": 0.4226, "30-44": 0.373, "45-64": 0.2798, "65+": 0.3482 },
      race: { "white": 0.1849, "black": 0.728, "hispanic": 0.42, "asian": 0.4827, "other": 0.3254 },
      education: { "no-hs": 0.3352, "hs": 0.3033, "some-college": 0.3029, "bachelors-plus": 0.4459 },
  },
  "02": {
      sex: { "male": 0.3785, "female": 0.4816 },
      age: { "18-29": 0.4828, "30-44": 0.4448, "45-64": 0.3731, "65+": 0.4219 },
      race: { "white": 0.3949, "black": 0.8439, "hispanic": 0.5006, "asian": 0.5538, "other": 0.4004 },
      education: { "no-hs": 0.3872, "hs": 0.3838, "some-college": 0.3832, "bachelors-plus": 0.5204 },
  },
  "04": {
      sex: { "male": 0.4372, "female": 0.5368 },
      age: { "18-29": 0.557, "30-44": 0.5129, "45-64": 0.4323, "65+": 0.4697 },
      race: { "white": 0.4132, "black": 0.8784, "hispanic": 0.5636, "asian": 0.5851, "other": 0.432 },
      education: { "no-hs": 0.4592, "hs": 0.4477, "some-college": 0.4389, "bachelors-plus": 0.5724 },
  },
  "05": {
      sex: { "male": 0.2872, "female": 0.3869 },
      age: { "18-29": 0.4048, "30-44": 0.361, "45-64": 0.2778, "65+": 0.3371 },
      race: { "white": 0.2362, "black": 0.7489, "hispanic": 0.4192, "asian": 0.4801, "other": 0.3224 },
      education: { "no-hs": 0.3229, "hs": 0.2923, "some-college": 0.3011, "bachelors-plus": 0.4472 },
  },
  "06": {
      sex: { "male": 0.5532, "female": 0.6582 },
      age: { "18-29": 0.641, "30-44": 0.6455, "45-64": 0.5685, "65+": 0.575 },
      race: { "white": 0.5492, "black": 0.9222, "hispanic": 0.593, "asian": 0.7085, "other": 0.4711 },
      education: { "no-hs": 0.5479, "hs": 0.5073, "some-college": 0.5047, "bachelors-plus": 0.7602 },
  },
  "08": {
      sex: { "male": 0.51, "female": 0.6112 },
      age: { "18-29": 0.6168, "30-44": 0.5863, "45-64": 0.5063, "65+": 0.5436 },
      race: { "white": 0.5332, "black": 0.9173, "hispanic": 0.5895, "asian": 0.6246, "other": 0.4742 },
      education: { "no-hs": 0.4726, "hs": 0.4737, "some-college": 0.4776, "bachelors-plus": 0.6604 },
  },
  "09": {
      sex: { "male": 0.521, "female": 0.6255 },
      age: { "18-29": 0.628, "30-44": 0.5961, "45-64": 0.5327, "65+": 0.5689 },
      race: { "white": 0.5195, "black": 0.9242, "hispanic": 0.5877, "asian": 0.6303, "other": 0.4784 },
      education: { "no-hs": 0.4964, "hs": 0.5108, "some-college": 0.5093, "bachelors-plus": 0.6651 },
  },
  "10": {
      sex: { "male": 0.522, "female": 0.6251 },
      age: { "18-29": 0.6331, "30-44": 0.5981, "45-64": 0.5287, "65+": 0.5732 },
      race: { "white": 0.4649, "black": 0.9051, "hispanic": 0.5611, "asian": 0.6135, "other": 0.4617 },
      education: { "no-hs": 0.5209, "hs": 0.5266, "some-college": 0.5262, "bachelors-plus": 0.6657 },
  },
  "12": {
      sex: { "male": 0.3881, "female": 0.4906 },
      age: { "18-29": 0.5199, "30-44": 0.4777, "45-64": 0.3848, "65+": 0.4222 },
      race: { "white": 0.3173, "black": 0.8453, "hispanic": 0.4492, "asian": 0.5577, "other": 0.4036 },
      education: { "no-hs": 0.4221, "hs": 0.398, "some-college": 0.388, "bachelors-plus": 0.5244 },
  },
  "13": {
      sex: { "male": 0.4413, "female": 0.5521 },
      age: { "18-29": 0.5675, "30-44": 0.5336, "45-64": 0.4391, "65+": 0.477 },
      race: { "white": 0.2788, "black": 0.8573, "hispanic": 0.4974, "asian": 0.5566, "other": 0.3981 },
      education: { "no-hs": 0.442, "hs": 0.4312, "some-college": 0.4392, "bachelors-plus": 0.6154 },
  },
  "15": {
      sex: { "male": 0.5681, "female": 0.6703 },
      age: { "18-29": 0.6722, "30-44": 0.6409, "45-64": 0.5729, "65+": 0.6156 },
      race: { "white": 0.5395, "black": 0.9707, "hispanic": 0.6334, "asian": 0.7033, "other": 0.5491 },
      education: { "no-hs": 0.5525, "hs": 0.5673, "some-college": 0.5703, "bachelors-plus": 0.7117 },
  },
  "16": {
      sex: { "male": 0.2622, "female": 0.3644 },
      age: { "18-29": 0.3744, "30-44": 0.3325, "45-64": 0.256, "65+": 0.3102 },
      race: { "white": 0.285, "black": 0.7771, "hispanic": 0.4267, "asian": 0.487, "other": 0.3322 },
      education: { "no-hs": 0.289, "hs": 0.272, "some-college": 0.265, "bachelors-plus": 0.4048 },
  },
  "17": {
      sex: { "male": 0.5083, "female": 0.6226 },
      age: { "18-29": 0.6278, "30-44": 0.6006, "45-64": 0.5195, "65+": 0.5396 },
      race: { "white": 0.4701, "black": 0.921, "hispanic": 0.6152, "asian": 0.6308, "other": 0.4582 },
      education: { "no-hs": 0.4916, "hs": 0.4858, "some-college": 0.4879, "bachelors-plus": 0.697 },
  },
  "18": {
      sex: { "male": 0.3559, "female": 0.4605 },
      age: { "18-29": 0.4757, "30-44": 0.4354, "45-64": 0.3466, "65+": 0.4061 },
      race: { "white": 0.3387, "black": 0.8615, "hispanic": 0.508, "asian": 0.5579, "other": 0.4065 },
      education: { "no-hs": 0.3908, "hs": 0.3572, "some-college": 0.3663, "bachelors-plus": 0.5135 },
  },
  "19": {
      sex: { "male": 0.3792, "female": 0.4816 },
      age: { "18-29": 0.4899, "30-44": 0.4526, "45-64": 0.3761, "65+": 0.4263 },
      race: { "white": 0.4004, "black": 0.8574, "hispanic": 0.5123, "asian": 0.5674, "other": 0.4151 },
      education: { "no-hs": 0.3972, "hs": 0.3864, "some-college": 0.3857, "bachelors-plus": 0.5255 },
  },
  "20": {
      sex: { "male": 0.3585, "female": 0.4611 },
      age: { "18-29": 0.4671, "30-44": 0.4308, "45-64": 0.3547, "65+": 0.4064 },
      race: { "white": 0.3618, "black": 0.8344, "hispanic": 0.4859, "asian": 0.5464, "other": 0.3921 },
      education: { "no-hs": 0.3742, "hs": 0.3605, "some-college": 0.3574, "bachelors-plus": 0.4998 },
  },
  "21": {
      sex: { "male": 0.2924, "female": 0.3947 },
      age: { "18-29": 0.4172, "30-44": 0.3711, "45-64": 0.2786, "65+": 0.346 },
      race: { "white": 0.286, "black": 0.8268, "hispanic": 0.4796, "asian": 0.5333, "other": 0.3788 },
      education: { "no-hs": 0.3284, "hs": 0.2877, "some-college": 0.3043, "bachelors-plus": 0.4598 },
  },
  "22": {
      sex: { "male": 0.3416, "female": 0.4432 },
      age: { "18-29": 0.4569, "30-44": 0.4162, "45-64": 0.3359, "65+": 0.3931 },
      race: { "white": 0.2137, "black": 0.7234, "hispanic": 0.4227, "asian": 0.4826, "other": 0.3242 },
      education: { "no-hs": 0.3752, "hs": 0.3488, "some-college": 0.3585, "bachelors-plus": 0.4945 },
  },
  "23": {
      sex: { "male": 0.4785, "female": 0.5813 },
      age: { "18-29": 0.5903, "30-44": 0.5555, "45-64": 0.4856, "65+": 0.5304 },
      race: { "white": 0.5226, "black": 0.9314, "hispanic": 0.5887, "asian": 0.6415, "other": 0.4913 },
      education: { "no-hs": 0.4741, "hs": 0.4788, "some-college": 0.4799, "bachelors-plus": 0.6234 },
  },
  "24": {
      sex: { "male": 0.6013, "female": 0.7149 },
      age: { "18-29": 0.7045, "30-44": 0.6875, "45-64": 0.6267, "65+": 0.6404 },
      race: { "white": 0.505, "black": 0.9714, "hispanic": 0.6051, "asian": 0.6435, "other": 0.4846 },
      education: { "no-hs": 0.5575, "hs": 0.5821, "some-college": 0.5809, "bachelors-plus": 0.7683 },
  },
  "25": {
      sex: { "male": 0.5825, "female": 0.6908 },
      age: { "18-29": 0.6943, "30-44": 0.6628, "45-64": 0.597, "65+": 0.6187 },
      race: { "white": 0.6175, "black": 0.9612, "hispanic": 0.6291, "asian": 0.6717, "other": 0.5135 },
      education: { "no-hs": 0.525, "hs": 0.5467, "some-college": 0.5427, "bachelors-plus": 0.7466 },
  },
  "26": {
      sex: { "male": 0.4422, "female": 0.5545 },
      age: { "18-29": 0.5647, "30-44": 0.5283, "45-64": 0.4464, "65+": 0.4877 },
      race: { "white": 0.4248, "black": 0.9009, "hispanic": 0.5378, "asian": 0.594, "other": 0.4368 },
      education: { "no-hs": 0.4538, "hs": 0.4447, "some-college": 0.4504, "bachelors-plus": 0.605 },
  },
  "27": {
      sex: { "male": 0.4755, "female": 0.5806 },
      age: { "18-29": 0.5906, "30-44": 0.5587, "45-64": 0.4754, "65+": 0.5128 },
      race: { "white": 0.4867, "black": 0.9229, "hispanic": 0.5688, "asian": 0.6243, "other": 0.4662 },
      education: { "no-hs": 0.4592, "hs": 0.4488, "some-college": 0.4551, "bachelors-plus": 0.6439 },
  },
  "28": {
      sex: { "male": 0.3345, "female": 0.4335 },
      age: { "18-29": 0.4492, "30-44": 0.4079, "45-64": 0.3286, "65+": 0.3867 },
      race: { "white": 0.1921, "black": 0.6891, "hispanic": 0.3905, "asian": 0.4487, "other": 0.2919 },
      education: { "no-hs": 0.3664, "hs": 0.3507, "some-college": 0.3478, "bachelors-plus": 0.4879 },
  },
  "29": {
      sex: { "male": 0.358, "female": 0.467 },
      age: { "18-29": 0.4821, "30-44": 0.4423, "45-64": 0.3524, "65+": 0.4079 },
      race: { "white": 0.3362, "black": 0.8813, "hispanic": 0.5108, "asian": 0.565, "other": 0.4088 },
      education: { "no-hs": 0.3868, "hs": 0.3507, "some-college": 0.3652, "bachelors-plus": 0.5238 },
  },
  "30": {
      sex: { "male": 0.3477, "female": 0.4499 },
      age: { "18-29": 0.4599, "30-44": 0.4201, "45-64": 0.3451, "65+": 0.394 },
      race: { "white": 0.3886, "black": 0.8454, "hispanic": 0.5018, "asian": 0.5557, "other": 0.4018 },
      education: { "no-hs": 0.3617, "hs": 0.3507, "some-college": 0.349, "bachelors-plus": 0.4859 },
  },
  "31": {
      sex: { "male": 0.346, "female": 0.4485 },
      age: { "18-29": 0.4584, "30-44": 0.4196, "45-64": 0.3408, "65+": 0.3902 },
      race: { "white": 0.3525, "black": 0.8316, "hispanic": 0.4825, "asian": 0.5411, "other": 0.3873 },
      education: { "no-hs": 0.363, "hs": 0.3473, "some-college": 0.3445, "bachelors-plus": 0.491 },
  },
  "32": {
      sex: { "male": 0.4346, "female": 0.5372 },
      age: { "18-29": 0.5444, "30-44": 0.5073, "45-64": 0.4351, "65+": 0.4816 },
      race: { "white": 0.3987, "black": 0.8517, "hispanic": 0.5049, "asian": 0.5619, "other": 0.4101 },
      education: { "no-hs": 0.4467, "hs": 0.4484, "some-college": 0.448, "bachelors-plus": 0.5836 },
  },
  "33": {
      sex: { "male": 0.4611, "female": 0.5632 },
      age: { "18-29": 0.5722, "30-44": 0.5363, "45-64": 0.4659, "65+": 0.511 },
      race: { "white": 0.5013, "black": 0.9179, "hispanic": 0.5761, "asian": 0.6286, "other": 0.4773 },
      education: { "no-hs": 0.4537, "hs": 0.4563, "some-college": 0.4563, "bachelors-plus": 0.5951 },
  },
  "34": {
      sex: { "male": 0.4871, "female": 0.5911 },
      age: { "18-29": 0.5984, "30-44": 0.5709, "45-64": 0.496, "65+": 0.5245 },
      race: { "white": 0.4422, "black": 0.901, "hispanic": 0.5589, "asian": 0.6035, "other": 0.4443 },
      education: { "no-hs": 0.4729, "hs": 0.4798, "some-college": 0.474, "bachelors-plus": 0.6233 },
  },
  "35": {
      sex: { "male": 0.4779, "female": 0.5805 },
      age: { "18-29": 0.5848, "30-44": 0.5504, "45-64": 0.4803, "65+": 0.5251 },
      race: { "white": 0.4722, "black": 0.9028, "hispanic": 0.5723, "asian": 0.6132, "other": 0.4652 },
      education: { "no-hs": 0.4802, "hs": 0.4861, "some-college": 0.4891, "bachelors-plus": 0.6273 },
  },
  "36": {
      sex: { "male": 0.5146, "female": 0.6454 },
      age: { "18-29": 0.6425, "30-44": 0.6346, "45-64": 0.5257, "65+": 0.5507 },
      race: { "white": 0.484, "black": 0.9372, "hispanic": 0.6179, "asian": 0.6263, "other": 0.4629 },
      education: { "no-hs": 0.5189, "hs": 0.4905, "some-college": 0.4829, "bachelors-plus": 0.7151 },
  },
  "37": {
      sex: { "male": 0.4325, "female": 0.5376 },
      age: { "18-29": 0.5552, "30-44": 0.5211, "45-64": 0.4293, "65+": 0.469 },
      race: { "white": 0.3639, "black": 0.8478, "hispanic": 0.5141, "asian": 0.5758, "other": 0.4116 },
      education: { "no-hs": 0.4311, "hs": 0.4128, "some-college": 0.418, "bachelors-plus": 0.6111 },
  },
  "38": {
      sex: { "male": 0.2628, "female": 0.3661 },
      age: { "18-29": 0.3673, "30-44": 0.3294, "45-64": 0.257, "65+": 0.3068 },
      race: { "white": 0.2859, "black": 0.7588, "hispanic": 0.4154, "asian": 0.4697, "other": 0.3153 },
      education: { "no-hs": 0.2806, "hs": 0.2708, "some-college": 0.2656, "bachelors-plus": 0.4042 },
  },
  "39": {
      sex: { "male": 0.3926, "female": 0.5027 },
      age: { "18-29": 0.5241, "30-44": 0.4813, "45-64": 0.3845, "65+": 0.4404 },
      race: { "white": 0.3696, "black": 0.8993, "hispanic": 0.5277, "asian": 0.5796, "other": 0.4259 },
      education: { "no-hs": 0.4197, "hs": 0.3799, "some-college": 0.4036, "bachelors-plus": 0.5673 },
  },
  "40": {
      sex: { "male": 0.2689, "female": 0.3707 },
      age: { "18-29": 0.3846, "30-44": 0.3399, "45-64": 0.2576, "65+": 0.3217 },
      race: { "white": 0.2465, "black": 0.7741, "hispanic": 0.4201, "asian": 0.4891, "other": 0.3127 },
      education: { "no-hs": 0.3094, "hs": 0.2712, "some-college": 0.2771, "bachelors-plus": 0.4246 },
  },
  "41": {
      sex: { "male": 0.5264, "female": 0.6296 },
      age: { "18-29": 0.6306, "30-44": 0.6069, "45-64": 0.5331, "65+": 0.5636 },
      race: { "white": 0.5673, "black": 0.9365, "hispanic": 0.6068, "asian": 0.6535, "other": 0.5001 },
      education: { "no-hs": 0.5001, "hs": 0.5102, "some-college": 0.5246, "bachelors-plus": 0.6855 },
  },
  "42": {
      sex: { "male": 0.4308, "female": 0.5518 },
      age: { "18-29": 0.5676, "30-44": 0.5358, "45-64": 0.4321, "65+": 0.4714 },
      race: { "white": 0.42, "black": 0.9365, "hispanic": 0.555, "asian": 0.6058, "other": 0.4458 },
      education: { "no-hs": 0.4416, "hs": 0.4042, "some-college": 0.4375, "bachelors-plus": 0.6251 },
  },
  "44": {
      sex: { "male": 0.5176, "female": 0.6209 },
      age: { "18-29": 0.6262, "30-44": 0.5916, "45-64": 0.5229, "65+": 0.5654 },
      race: { "white": 0.5341, "black": 0.9478, "hispanic": 0.6117, "asian": 0.6571, "other": 0.5068 },
      education: { "no-hs": 0.5108, "hs": 0.518, "some-college": 0.517, "bachelors-plus": 0.6605 },
  },
  "45": {
      sex: { "male": 0.3609, "female": 0.4601 },
      age: { "18-29": 0.4826, "30-44": 0.4382, "45-64": 0.3528, "65+": 0.4092 },
      race: { "white": 0.2629, "black": 0.7779, "hispanic": 0.453, "asian": 0.5141, "other": 0.3578 },
      education: { "no-hs": 0.3854, "hs": 0.3672, "some-college": 0.3665, "bachelors-plus": 0.5033 },
  },
  "46": {
      sex: { "male": 0.2999, "female": 0.4025 },
      age: { "18-29": 0.4098, "30-44": 0.3714, "45-64": 0.2973, "65+": 0.3465 },
      race: { "white": 0.33, "black": 0.7937, "hispanic": 0.4501, "asian": 0.5042, "other": 0.3497 },
      education: { "no-hs": 0.3155, "hs": 0.307, "some-college": 0.3057, "bachelors-plus": 0.4429 },
  },
  "47": {
      sex: { "male": 0.2998, "female": 0.3972 },
      age: { "18-29": 0.4233, "30-44": 0.3751, "45-64": 0.2825, "65+": 0.3528 },
      race: { "white": 0.2507, "black": 0.7486, "hispanic": 0.4472, "asian": 0.512, "other": 0.3562 },
      education: { "no-hs": 0.3445, "hs": 0.2995, "some-college": 0.3068, "bachelors-plus": 0.4411 },
  },
  "48": {
      sex: { "male": 0.3933, "female": 0.4913 },
      age: { "18-29": 0.5245, "30-44": 0.4766, "45-64": 0.3661, "65+": 0.4199 },
      race: { "white": 0.2618, "black": 0.8373, "hispanic": 0.4913, "asian": 0.5623, "other": 0.4034 },
      education: { "no-hs": 0.4601, "hs": 0.3926, "some-college": 0.37, "bachelors-plus": 0.532 },
  },
  "49": {
      sex: { "male": 0.3469, "female": 0.4494 },
      age: { "18-29": 0.4475, "30-44": 0.409, "45-64": 0.3391, "65+": 0.3966 },
      race: { "white": 0.3678, "black": 0.8384, "hispanic": 0.4881, "asian": 0.5477, "other": 0.3936 },
      education: { "no-hs": 0.3659, "hs": 0.3548, "some-college": 0.3441, "bachelors-plus": 0.476 },
  },
  "50": {
      sex: { "male": 0.6076, "female": 0.7104 },
      age: { "18-29": 0.7155, "30-44": 0.6807, "45-64": 0.6142, "65+": 0.6571 },
      race: { "white": 0.6546, "black": 0.98, "hispanic": 0.7045, "asian": 0.7572, "other": 0.607 },
      education: { "no-hs": 0.5861, "hs": 0.5969, "some-college": 0.5957, "bachelors-plus": 0.7424 },
  },
  "51": {
      sex: { "male": 0.4812, "female": 0.5852 },
      age: { "18-29": 0.5925, "30-44": 0.5683, "45-64": 0.4851, "65+": 0.512 },
      race: { "white": 0.4174, "black": 0.8934, "hispanic": 0.5584, "asian": 0.6111, "other": 0.4438 },
      education: { "no-hs": 0.4543, "hs": 0.4467, "some-college": 0.4595, "bachelors-plus": 0.6461 },
  },
  "53": {
      sex: { "male": 0.5447, "female": 0.6442 },
      age: { "18-29": 0.645, "30-44": 0.6276, "45-64": 0.5454, "65+": 0.5726 },
      race: { "white": 0.5773, "black": 0.9349, "hispanic": 0.5861, "asian": 0.6695, "other": 0.4982 },
      education: { "no-hs": 0.4893, "hs": 0.5027, "some-college": 0.5198, "bachelors-plus": 0.7237 },
  },
  "54": {
      sex: { "male": 0.2349, "female": 0.336 },
      age: { "18-29": 0.355, "30-44": 0.3137, "45-64": 0.2299, "65+": 0.2836 },
      race: { "white": 0.2627, "black": 0.7655, "hispanic": 0.4233, "asian": 0.4774, "other": 0.3231 },
      education: { "no-hs": 0.2714, "hs": 0.2424, "some-college": 0.256, "bachelors-plus": 0.395 },
  },
  "55": {
      sex: { "male": 0.4462, "female": 0.553 },
      age: { "18-29": 0.5702, "30-44": 0.5294, "45-64": 0.4441, "65+": 0.4877 },
      race: { "white": 0.4632, "black": 0.9069, "hispanic": 0.557, "asian": 0.6038, "other": 0.4503 },
      education: { "no-hs": 0.4522, "hs": 0.4459, "some-college": 0.4471, "bachelors-plus": 0.605 },
  },
  "56": {
      sex: { "male": 0.2147, "female": 0.318 },
      age: { "18-29": 0.3271, "30-44": 0.2862, "45-64": 0.2112, "65+": 0.2621 },
      race: { "white": 0.2429, "black": 0.7256, "hispanic": 0.3781, "asian": 0.4359, "other": 0.2814 },
      education: { "no-hs": 0.239, "hs": 0.2252, "some-college": 0.2197, "bachelors-plus": 0.3603 },
  },
};
